import { PERMISSIONS } from "./permissions";

export const ROLES = {
  ADMIN: "admin",
  USER: "user",
};

const USER_PERMISSIONS = [
  PERMISSIONS.DELETE_OWN_REVIEW,
  PERMISSIONS.EDIT_OWN_REVIEW,
  PERMISSIONS.CREATE_OWN_REVIEW,
  PERMISSIONS.DELETE_OWN_USER,
  PERMISSIONS.UPDATE_OWN_PWD,
  PERMISSIONS.VIEW_OWN_PROFILE,
];

const ADMIN_PERMISSIONS = [
  ...USER_PERMISSIONS,
  PERMISSIONS.VIEW_ANY_PROFILE,
  PERMISSIONS.DELETE_ANY_REVIEW,
  PERMISSIONS.EDIT_ANY_REVIEW,
  PERMISSIONS.DELETE_ANY_USER,
];

export const ROLE_PERMISSIONS = new Map<string, Array<string>>([
  [ROLES.USER, USER_PERMISSIONS],
  [ROLES.ADMIN, ADMIN_PERMISSIONS],
]);
